CREATE TABLE `update_stock` (
	`id` integer PRIMARY KEY,
	`product_id` integer NOT NULL,
	`movement_type` text NOT NULL,
	`qunt_remove` integer DEFAULT 0 NOT NULL,
	`qunt_add` integer DEFAULT 0 NOT NULL,
	`dt_update` text NOT NULL,
	`sm_code` text NOT NULL,
	`bar_code` text NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`value` text,
	`cost` text,
	`amount` text,
	`ncm` text,
	`cst` text NOT NULL,
	`csosn` text NOT NULL,
	`icms` real NOT NULL,
	`status` integer NOT NULL
);
